### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by dskuratovich** [EgorRepnikov/artaeum#2]
I noticed that currently the app doesn't use lazy loading feature of Angular Modules; so I think it could be improved, using that we could improve home page loading, reduce main files size and so on.
Probably to do this we'd need to upgrade some dependencies like webpack, webpack-cli but in generally it'd not affect so much!

Thanks in advance.

**Comment by EgorRepnikov** [comment]
I'm going to add a lazy-loading in the future. Before I tried to implement it, but something went wrong. I don’t remember exactly why, but it seems: there was a conflict with the SSR. Therefore, I postponed this task.

**Comment by dskuratovich** [comment]
Okay, I see the point. I just noticed that the main size is about ~900kb, so this is sort of big size I think for such tiny application
