### ISSUE TITLE
Realistic mocked data

### ISSUE THREAD

**Issue by dskuratovich** [EgorRepnikov/artaeum#3]
I noticed there are some mocks in the application used.
That's really cool approach to get an ability to use an application without data, but I'd suggest to modify the mocks to get it more real

Thanks in advance.

**Comment by EgorRepnikov** [comment]
I'm afraid, I didn't understand what you mean by "more real". Is it about mock json-server?

**Comment by dskuratovich** [comment]
Exactly, now at some points it looks like "nan" or "undefined" on the mocked page, so I think it'd be better to get the data more realistic

**Comment by EgorRepnikov** [comment]
Got it. I forgot about it... I should to fix. Thanks!

**Comment by dskuratovich** [comment]
No problem, I just noticed that when I tried to run the application locally
