### ISSUE TITLE
Split the application

### ISSUE THREAD

**Issue by dskuratovich** [EgorRepnikov/artaeum#4]
Currently you have many application (services, ui) in the only repo, so that's actually not the best approach.
I'd recommend you to split them

**Comment by EgorRepnikov** [comment]
This is a good idea. I thought about it. And probably soon I will split the project. I'm not sure what to do with the backend (services are strongly connected with each other at least with service discovery and gateway), but it would be nice to make a separate repository for the frontend.

**Comment by dskuratovich** [comment]
Yeah, at least extract the front repo to dedicated one would be good!
